#ifndef NEBU_INPUT_IDS_H
#define NEBU_INPUT_IDS_H

/*
 * Stable input identifiers used by GLTron and stored in its preferences.
 *
 * Keyboard values intentionally retain the SDL 1.2 numeric ABI.  Backends
 * translate their native key representation to these values before invoking
 * game callbacks; saved bindings must never contain backend-native values.
 */
typedef int SystemInputId;

enum {
	GLTRON_INPUT_INVALID = -1,
	GLTRON_INPUT_KEY_UNKNOWN = 0,
	GLTRON_INPUT_KEY_BACKSPACE = 8,
	GLTRON_INPUT_KEY_TAB = 9,
	GLTRON_INPUT_KEY_CLEAR = 12,
	GLTRON_INPUT_KEY_RETURN = 13,
	GLTRON_INPUT_KEY_PAUSE = 19,
	GLTRON_INPUT_KEY_ESCAPE = 27,
	GLTRON_INPUT_KEY_SPACE = 32,
	GLTRON_INPUT_KEY_DELETE = 127,

	GLTRON_INPUT_KEY_WORLD_FIRST = 160,
	GLTRON_INPUT_KEY_WORLD_LAST = 255,

	GLTRON_INPUT_KEY_KP0 = 256,
	GLTRON_INPUT_KEY_KP1 = 257,
	GLTRON_INPUT_KEY_KP2 = 258,
	GLTRON_INPUT_KEY_KP3 = 259,
	GLTRON_INPUT_KEY_KP4 = 260,
	GLTRON_INPUT_KEY_KP5 = 261,
	GLTRON_INPUT_KEY_KP6 = 262,
	GLTRON_INPUT_KEY_KP7 = 263,
	GLTRON_INPUT_KEY_KP8 = 264,
	GLTRON_INPUT_KEY_KP9 = 265,
	GLTRON_INPUT_KEY_KP_PERIOD = 266,
	GLTRON_INPUT_KEY_KP_DIVIDE = 267,
	GLTRON_INPUT_KEY_KP_MULTIPLY = 268,
	GLTRON_INPUT_KEY_KP_MINUS = 269,
	GLTRON_INPUT_KEY_KP_PLUS = 270,
	GLTRON_INPUT_KEY_KP_ENTER = 271,
	GLTRON_INPUT_KEY_KP_EQUALS = 272,

	GLTRON_INPUT_KEY_UP = 273,
	GLTRON_INPUT_KEY_DOWN = 274,
	GLTRON_INPUT_KEY_RIGHT = 275,
	GLTRON_INPUT_KEY_LEFT = 276,
	GLTRON_INPUT_KEY_INSERT = 277,
	GLTRON_INPUT_KEY_HOME = 278,
	GLTRON_INPUT_KEY_END = 279,
	GLTRON_INPUT_KEY_PAGEUP = 280,
	GLTRON_INPUT_KEY_PAGEDOWN = 281,

	GLTRON_INPUT_KEY_F1 = 282,
	GLTRON_INPUT_KEY_F2 = 283,
	GLTRON_INPUT_KEY_F3 = 284,
	GLTRON_INPUT_KEY_F4 = 285,
	GLTRON_INPUT_KEY_F5 = 286,
	GLTRON_INPUT_KEY_F6 = 287,
	GLTRON_INPUT_KEY_F7 = 288,
	GLTRON_INPUT_KEY_F8 = 289,
	GLTRON_INPUT_KEY_F9 = 290,
	GLTRON_INPUT_KEY_F10 = 291,
	GLTRON_INPUT_KEY_F11 = 292,
	GLTRON_INPUT_KEY_F12 = 293,
	GLTRON_INPUT_KEY_F13 = 294,
	GLTRON_INPUT_KEY_F14 = 295,
	GLTRON_INPUT_KEY_F15 = 296,

	GLTRON_INPUT_KEY_NUMLOCK = 300,
	GLTRON_INPUT_KEY_CAPSLOCK = 301,
	GLTRON_INPUT_KEY_SCROLLOCK = 302,
	GLTRON_INPUT_KEY_RSHIFT = 303,
	GLTRON_INPUT_KEY_LSHIFT = 304,
	GLTRON_INPUT_KEY_RCTRL = 305,
	GLTRON_INPUT_KEY_LCTRL = 306,
	GLTRON_INPUT_KEY_RALT = 307,
	GLTRON_INPUT_KEY_LALT = 308,
	GLTRON_INPUT_KEY_RMETA = 309,
	GLTRON_INPUT_KEY_LMETA = 310,
	GLTRON_INPUT_KEY_LSUPER = 311,
	GLTRON_INPUT_KEY_RSUPER = 312,
	GLTRON_INPUT_KEY_MODE = 313,
	GLTRON_INPUT_KEY_COMPOSE = 314,
	GLTRON_INPUT_KEY_HELP = 315,
	GLTRON_INPUT_KEY_PRINT = 316,
	GLTRON_INPUT_KEY_SYSREQ = 317,
	GLTRON_INPUT_KEY_BREAK = 318,
	GLTRON_INPUT_KEY_MENU = 319,
	GLTRON_INPUT_KEY_POWER = 320,
	GLTRON_INPUT_KEY_EURO = 321,
	GLTRON_INPUT_KEY_UNDO = 322,
	GLTRON_INPUT_KEY_LAST = 322,

	GLTRON_INPUT_JOY_OFFSET = 32,
	GLTRON_INPUT_CUSTOM_FIRST = 512,
	GLTRON_INPUT_JOY_LEFT = 512,
	GLTRON_INPUT_JOY_RIGHT = 513,
	GLTRON_INPUT_JOY_UP = 514,
	GLTRON_INPUT_JOY_DOWN = 515,
	GLTRON_INPUT_JOY_BUTTON_0 = 516,
	GLTRON_INPUT_JOY_BUTTON_1 = 517,
	GLTRON_INPUT_JOY_BUTTON_2 = 518,
	GLTRON_INPUT_JOY_BUTTON_3 = 519,
	GLTRON_INPUT_JOY_BUTTON_4 = 520,
	GLTRON_INPUT_JOY_BUTTON_5 = 521,
	GLTRON_INPUT_JOY_BUTTON_6 = 522,
	GLTRON_INPUT_JOY_BUTTON_7 = 523,
	GLTRON_INPUT_JOY_BUTTON_8 = 524,
	GLTRON_INPUT_JOY_BUTTON_9 = 525,
	GLTRON_INPUT_JOY_BUTTON_10 = 526,
	GLTRON_INPUT_JOY_BUTTON_11 = 527,
	GLTRON_INPUT_JOY_BUTTON_12 = 528,
	GLTRON_INPUT_JOY_BUTTON_13 = 529,
	GLTRON_INPUT_JOY_BUTTON_14 = 530,
	GLTRON_INPUT_JOY_BUTTON_15 = 531,
	GLTRON_INPUT_JOY_BUTTON_16 = 532,
	GLTRON_INPUT_JOY_BUTTON_17 = 533,
	GLTRON_INPUT_JOY_BUTTON_18 = 534,
	GLTRON_INPUT_JOY_BUTTON_19 = 535
};

enum {
	GLTRON_INPUT_STATE_DOWN = 0,
	GLTRON_INPUT_STATE_UP = 1,
	GLTRON_INPUT_JOY_SLOT_COUNT = 2,
	GLTRON_INPUT_JOY_AXIS_COUNT = 2,
	GLTRON_INPUT_JOY_BUTTON_COUNT = 20,
	GLTRON_INPUT_JOY_AXIS_MAX = 32767
};

typedef struct {
	signed char direction[GLTRON_INPUT_JOY_SLOT_COUNT]
	                     [GLTRON_INPUT_JOY_AXIS_COUNT];
} SystemJoystickTranslator;

typedef struct {
	int state;
	SystemInputId id;
} SystemInputTransition;

float SystemClampJoyThreshold(float threshold);
void SystemJoystickTranslatorReset(SystemJoystickTranslator *translator);
int SystemJoystickTranslatorResetSlot(SystemJoystickTranslator *translator,
											int slot);
int SystemTranslateJoystickAxis(SystemJoystickTranslator *translator,
								int slot, int axis, int value,
								float threshold,
								SystemInputTransition transitions[2]);
int SystemTranslateJoystickButton(int slot, int button, int state,
									SystemInputTransition *transition);

#endif
